version: 0.2

env:
  variables:
    key: "value"
    key: "value"
  parameter-store:
    key: "value"
    key: "value"
            
phases:
  install:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - npm install -g n
      - n latest
      - npm update -g npm
      - npm install
      - npm -g --unsafe-perm install node-sass
      - npm install
  build:
    commands:
      - ng build
  post_build:
    commands:
      - aws s3 sync dist s3://boo-koo.test.hassaku.net --delete